// <auto-generated />
using System;
using AvstickareApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AvstickareApi.Migrations
{
    [DbContext(typeof(AvstickareContext))]
    [Migration("20250512082141_InitialClean")]
    partial class InitialClean
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AvstickareApi.Models.AppUser", b =>
                {
                    b.Property<string>("AppUserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("AppUserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("AvstickareApi.Models.FavoritePlace", b =>
                {
                    b.Property<int>("FavoritePlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FavoritePlaceId"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MapServicePlaceId")
                        .HasColumnType("text");

                    b.Property<int?>("PlaceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FavoritePlaceId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("PlaceId");

                    b.ToTable("FavoritePlaces");
                });

            modelBuilder.Entity("AvstickareApi.Models.Place", b =>
                {
                    b.Property<int>("PlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlaceId"));

                    b.Property<string>("MapServicePlaceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PlaceId");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("AvstickareApi.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TripId"));

                    b.Property<string>("AppUserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromPlaceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FromPlacePlaceId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToPlaceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ToPlacePlaceId")
                        .HasColumnType("integer");

                    b.HasKey("TripId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("FromPlacePlaceId");

                    b.HasIndex("ToPlacePlaceId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("AvstickareApi.Models.TripStop", b =>
                {
                    b.Property<int>("TripStopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TripStopId"));

                    b.Property<string>("MapServicePlaceId")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int?>("PlaceId")
                        .HasColumnType("integer");

                    b.Property<int>("TripId")
                        .HasColumnType("integer");

                    b.HasKey("TripStopId");

                    b.HasIndex("PlaceId");

                    b.HasIndex("TripId");

                    b.ToTable("TripStops");
                });

            modelBuilder.Entity("AvstickareApi.Models.FavoritePlace", b =>
                {
                    b.HasOne("AvstickareApi.Models.AppUser", "User")
                        .WithMany("FavoritePlaces")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AvstickareApi.Models.Place", null)
                        .WithMany("FavoritePlaces")
                        .HasForeignKey("PlaceId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AvstickareApi.Models.Trip", b =>
                {
                    b.HasOne("AvstickareApi.Models.AppUser", "User")
                        .WithMany("Trips")
                        .HasForeignKey("AppUserId");

                    b.HasOne("AvstickareApi.Models.Place", "FromPlace")
                        .WithMany()
                        .HasForeignKey("FromPlacePlaceId");

                    b.HasOne("AvstickareApi.Models.Place", "ToPlace")
                        .WithMany()
                        .HasForeignKey("ToPlacePlaceId");

                    b.Navigation("FromPlace");

                    b.Navigation("ToPlace");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AvstickareApi.Models.TripStop", b =>
                {
                    b.HasOne("AvstickareApi.Models.Place", null)
                        .WithMany("TripStops")
                        .HasForeignKey("PlaceId");

                    b.HasOne("AvstickareApi.Models.Trip", "Trip")
                        .WithMany("TripStops")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("AvstickareApi.Models.AppUser", b =>
                {
                    b.Navigation("FavoritePlaces");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("AvstickareApi.Models.Place", b =>
                {
                    b.Navigation("FavoritePlaces");

                    b.Navigation("TripStops");
                });

            modelBuilder.Entity("AvstickareApi.Models.Trip", b =>
                {
                    b.Navigation("TripStops");
                });
#pragma warning restore 612, 618
        }
    }
}
